info:
  itle: Sample API,
  description: API of Movie rating app,
  contact: {
    name: API support,
    email: aryan@swagger.i
  }
paths: {
  /getmoviebyid : {
            get : {
                summary: Returns a movie,
                description: get movies,
                parameters: {
                    description: ID,
                    in: Params,
                    name: ID,
                    required: true,
                    type: int
                },
                produces": application/json, 
                response: 200
            }
        }  
}
swagger: "2.0"
